apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: ot-dashboard
stringData:
  pg-db.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://observability-prometheus-server.observability.svc:80
        editable: true
        access: proxy
        orgId: 1
        isDefault: true
        version: 1
        uid: prometheusdatasource
